// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgndhyxvlebwghbeqvzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbmRoeXh2bGVid2doYmVxdnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzI3NzYsImV4cCI6MjA3NDMwODc3Nn0.VnI6k9FFrIOr-c512qy5P3G8BvLiQhUFoMiPFKO9jcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});